### ISSUE TITLE
Implement prefix text collision attack in 2nd+ block?

### ISSUE THREAD

**Issue by kexinoh** [cr-marcstevens/hashclash#47]
Although there are prefix attacks and text collision attacks in the code, I don't quite understand how to set collision units for the second block (i.e. 65-128 bytes) or beyond in text collision attacks. If you can directly describe how to set it up, it's also possible.
Thank you to the author for bringing us such a great product!

**Comment by cr-marcstevens** [comment]
I don't understand your question.
The 2nd block is implemented in block2.cpp.
It is configured using this part of the script:
https://github.com/cr-marcstevens/hashclash/blob/77419e170ef3b29812819510ce3e5db6fdcf26f0/scripts/textcoll.sh#L29

**Comment by kexinoh** [comment]
Yes, I saw this sentence, but in the src/md5textcoll/block2.cpp inside I didn't find the location of the set. If I want to ensure that the first 128 bytes are the same and the 129-192 bytes are the alphabet, can I also modify this file?
Thank you for your help.

**Comment by cr-marcstevens** [comment]
The whole textcollision is of the following format:
```
file1: <prefixblocks = N*64 bytes> | textcoll-block1A   | textcoll-block2 | <suffix = K bytes>
file2: <prefixblocks = N*64 bytes> | textcoll-block1B   | textcoll-block2 | <suffix = K bytes>
       these prefixblocks must be    these blocks have
       the same                      1 byte difference 
```
The `textcoll-block2` are again the same for both files.
The only constraint for textcoll-block2 is that it needs to satisfy about 48 bitconditions for the attack.
There is really a lot of freedom how you construct textcoll-block2, feel free to adapt block2.cpp to your own needs.

**Comment by kexinoh** [comment]
Thank you, I am currently trying.
Thank you very much for your help！
