### ISSUE TITLE
missing M4 files

### ISSUE THREAD

**Issue by angea** [cr-marcstevens/hashclash#6]
I tried to compile and I had some errors like:
```
configure.ac:63: warning: AX_GCC_X86_AVX_XGETBV is m4_require'd but not m4_defun'd
m4/ax_simdext.m4:49: AX_EXT is expanded from...
```

I added `ax_gcc_x86_cpuid.m4` and `ax_gcc_x86_avx_xgetbv.m4` in `/m4/` to fix the problem.
(I can't create a PR at the moment)

**Comment by cr-marcstevens** [comment]
Will fix! 

Other solution: install package `autoconf-archive`

**Comment by cr-marcstevens** [comment]
Fixed
