### ISSUE TITLE
Different Boost versions between static release and configuration

### ISSUE THREAD

**Issue by angea** [cr-marcstevens/hashclash#7]
The default configuration uses Boost 1.57.0, while the static release uses 1.65.1.

Running a binary of the static release gives this error message:
```
./md5_fastcoll: error while loading shared libraries: libboost_filesystem.so.1.65.1: cannot open shared object file: No such file or directory
```

**Comment by cr-marcstevens** [comment]
Either can be used, but you should not reuse generated files between different boost versions.

Recommended version is 1.65.1. *


* (Unless you are an expert and want to use some of the archived generated files related to special attacks)

**Comment by cr-marcstevens** [comment]
Release v1.2 was faulty (accidentally linked to *dynamic* system boost libraries 1.65.1), release v1.2a is actually statically linked and again to default boost version 1.57.0.
